name: Docker
on: [push]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.ref_name }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Cache sccache
        uses: actions/cache@v4
        with:
          path: ~/.cache/sccache
          key: sccache-${{ runner.os }}-${{ github.ref_name }}
          restore-keys: |
            sccache-${{ runner.os }}-

      - name: Build Docker image with sccache
        run: |
          docker build \
            --build-arg SCCACHE_DIR=/sccache \
            --mount type=bind,source=${HOME}/.cache/sccache,target=/sccache \
            --cache-from type=local,src=/tmp/.buildx-cache \
            --cache-to type=local,dest=/tmp/.buildx-cache \
            -t ghcr.io/pay2exchange/pay2exchange-core:${{ github.ref_name }} .

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        run: |
          docker push ghcr.io/pay2exchange/pay2exchange-core:${{ github.ref_name }}
